import { useState, useEffect, useRef, useCallback, useMemo } from "react";
import { useTheme } from "./ThemeContext";
import ThemeToggle from "./ThemeToggle";

/*
 *  ╔══════════════════════════════════════════════════════════════════════╗
 *  ║  AEROLAB — CFD Wind Tunnel   ·   f1stories.gr                     ║
 *  ║  Lattice Boltzmann D2Q9 solver + bilinear RK2 particle tracer     ║
 *  ╚══════════════════════════════════════════════════════════════════════╝
 */

const SIM_W = 1000, SIM_H = 450;
const COLS = 400, ROWS = 180;
const DEFAULT_PARTICLES = 400, MAX_PARTICLES = 3000, TRAIL_LEN = 32;

// ── Colormaps ──
function buildTurboLUT() { const l = new Uint32Array(256); for (let i=0;i<256;i++){const t=i/255;const r=Math.max(0,Math.min(255,(34.61+t*(1172.33-t*(10793.56-t*(33300.12-t*(38394.49-t*14825.05)))))|0));const g=Math.max(0,Math.min(255,(23.31+t*(557.33+t*(1225.33-t*(3574.96-t*(1073.77+t*707.56)))))|0));const b=Math.max(0,Math.min(255,(27.2+t*(3211.1-t*(15327.97-t*(27814.0-t*(22569.18-t*6838.66)))))|0));l[i]=(255<<24)|(b<<16)|(g<<8)|r;}return l;}
function buildCoolWarmLUT() { const l = new Uint32Array(256); for(let i=0;i<256;i++){const t=i/255;let r,g,b;if(t<0.5){const s=t*2;r=(30+s*170)|0;g=(60+s*120)|0;b=(200-s*10)|0;}else{const s=(t-0.5)*2;r=(200+s*55)|0;g=(180-s*155)|0;b=(190-s*165)|0;}l[i]=(255<<24)|(Math.min(255,b)<<16)|(Math.min(255,g)<<8)|Math.min(255,r);}return l;}
const TURBO_LUT=buildTurboLUT(), COOLWARM_LUT=buildCoolWarmLUT();

// ── Geometry ──
function pointInPolygon(px,py,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const xi=poly[i][0],yi=poly[i][1],xj=poly[j][0],yj=poly[j][1];if(((yi>py)!==(yj>py))&&px<((xj-xi)*(py-yi))/(yj-yi)+xi)inside=!inside;}return inside;}
function normalizePolygon(pts){if(!pts||pts.length<3)return null;const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const rX=maxX-minX||1,rY=maxY-minY||1;return pts.map(p=>[(p[0]-minX)/rX,(p[1]-minY)/rY]);}
function transformPolygon(n,cx,cy,sx,sy,aoa){const rad=aoa*Math.PI/180,cos=Math.cos(rad),sin=Math.sin(rad);return n.map(([nx,ny])=>{const lx=(nx-0.5)*sx,ly=(ny-0.5)*sy;return[cx+cos*lx-sin*ly,cy+sin*lx+cos*ly];});}
function simplifyPolygon(pts,tol){if(pts.length<=4)return pts;const r=[pts[0]];for(let i=1;i<pts.length-1;i++){const prev=r[r.length-1],next=pts[i+1],curr=pts[i],dx=next[0]-prev[0],dy=next[1]-prev[1],len=Math.sqrt(dx*dx+dy*dy)||1,dist=Math.abs(dy*curr[0]-dx*curr[1]+next[0]*prev[1]-next[1]*prev[0])/len;if(dist>tol)r.push(curr);}r.push(pts[pts.length-1]);return r;}
function generatePreset(type){const p=[];if(type==="airfoil"){for(let t=0;t<=Math.PI*2;t+=0.04){const c=Math.cos(t),s=Math.sin(t);p.push([0.5+0.48*c*(0.5+0.5*c),0.5+0.18*s*(1+0.3*c)]);}}else if(type==="cylinder"){for(let t=0;t<=Math.PI*2;t+=0.05)p.push([0.5+0.45*Math.cos(t),0.5+0.45*Math.sin(t)]);}else if(type==="wedge"){p.push([0.05,0.25],[0.95,0.5],[0.05,0.75]);}else if(type==="bluff"){p.push([0.1,0.1],[0.9,0.1],[0.9,0.9],[0.1,0.9]);}return p;}

// ── Parsers ──
function parseSVGToPolygon(svgText,numPts=120){try{const doc=new DOMParser().parseFromString(svgText,"image/svg+xml");const el=doc.querySelector("path,polygon,polyline,rect,circle,ellipse");if(!el)return null;const tag=el.tagName.toLowerCase();let pts=[];if(tag==="polygon"||tag==="polyline"){const raw=el.getAttribute("points").trim().split(/[\s,]+/);for(let i=0;i<raw.length-1;i+=2)pts.push([parseFloat(raw[i]),parseFloat(raw[i+1])]);}else if(tag==="rect"){const x=+el.getAttribute("x")||0,y=+el.getAttribute("y")||0,w=+el.getAttribute("width"),h=+el.getAttribute("height");pts=[[x,y],[x+w,y],[x+w,y+h],[x,y+h]];}else if(tag==="circle"||tag==="ellipse"){const cx=+(el.getAttribute("cx")||0),cy=+(el.getAttribute("cy")||0),rx=+(el.getAttribute("r")||el.getAttribute("rx")||50),ry=+(el.getAttribute("r")||el.getAttribute("ry")||rx);for(let i=0;i<=numPts;i++){const t=(i/numPts)*Math.PI*2;pts.push([cx+rx*Math.cos(t),cy+ry*Math.sin(t)]);}}else if(tag==="path"){const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.style.cssText="position:absolute;visibility:hidden;width:0;height:0";document.body.appendChild(svg);const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",el.getAttribute("d"));svg.appendChild(p);const total=p.getTotalLength();for(let i=0;i<=numPts;i++){const pt=p.getPointAtLength((i/numPts)*total);pts.push([pt.x,pt.y]);}document.body.removeChild(svg);}return normalizePolygon(pts);}catch{return null;}}
function parseDXFToPolygon(t){const lines=t.split(/\r?\n/).map(l=>l.trim());const pts=[];let i=0,px=null;while(i<lines.length){const c=parseInt(lines[i],10);if(c===10&&i+1<lines.length){px=parseFloat(lines[i+1]);i+=2;}else if(c===20&&i+1<lines.length&&px!==null){const y=parseFloat(lines[i+1]);if(!isNaN(px)&&!isNaN(y))pts.push([px,y]);px=null;i+=2;}else i++;}return pts.length>2?normalizePolygon(pts):null;}
function traceImageToPolygon(imageData,w,h,numPts=100){const d=imageData.data;const edges=[];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4,bright=d[i]*0.3+d[i+1]*0.59+d[i+2]*0.11;if(bright<128){const nb=[(y-1)*w+(x-1),(y-1)*w+x,(y-1)*w+(x+1),y*w+(x-1),y*w+(x+1),(y+1)*w+(x-1),(y+1)*w+x,(y+1)*w+(x+1)];if(nb.some(n=>(d[n*4]*0.3+d[n*4+1]*0.59+d[n*4+2]*0.11)>=128))edges.push([x,y]);}}if(edges.length<5)return null;const cx=edges.reduce((s,p)=>s+p[0],0)/edges.length,cy=edges.reduce((s,p)=>s+p[1],0)/edges.length;edges.sort((a,b)=>Math.atan2(a[1]-cy,a[0]-cx)-Math.atan2(b[1]-cy,b[0]-cx));const step=Math.max(1,Math.floor(edges.length/numPts));return normalizePolygon(edges.filter((_,i)=>i%step===0));}

// ═══════════════════════════════════════════════════════════════════════════════
//  LATTICE BOLTZMANN D2Q9 SOLVER
// ═══════════════════════════════════════════════════════════════════════════════
const CX=[0,1,0,-1,0,1,-1,-1,1],CY=[0,0,1,0,-1,1,1,-1,-1],W=[4/9,1/9,1/9,1/9,1/9,1/36,1/36,1/36,1/36],OPP=[0,3,4,1,2,7,8,5,6];

class LBMSolver {
  constructor(cols,rows){
    this.cols=cols;this.rows=rows;this.n=cols*rows;
    this.f=new Float32Array(9*this.n);this.ft=new Float32Array(9*this.n);
    this.rho=new Float32Array(this.n);this.ux=new Float32Array(this.n);this.uy=new Float32Array(this.n);
    this.solid=new Uint8Array(this.n);this.curl=new Float32Array(this.n);
    this.omega=1.0;this._fieldBuf=new Float32Array(this.n);
    this._initEq(0.12,0);
  }
  _initEq(u0,v0){for(let j=0;j<this.rows;j++)for(let i=0;i<this.cols;i++){const k=j*this.cols+i;this.rho[k]=1;this.ux[k]=u0;this.uy[k]=v0;for(let d=0;d<9;d++){const cu=CX[d]*u0+CY[d]*v0;this.f[d*this.n+k]=W[d]*(1+3*cu+4.5*cu*cu-1.5*(u0*u0+v0*v0));}}}
  setViscosity(nu){this.omega=1/(3*nu+0.5);}
  buildSolid(poly){this.solid.fill(0);if(!poly)return;for(let j=0;j<this.rows;j++)for(let i=0;i<this.cols;i++)if(pointInPolygon(i+0.5,j+0.5,poly))this.solid[j*this.cols+i]=1;}
  step(inletU,turb){
    const{cols,rows,n,f,ft,rho,ux,uy,solid,omega}=this;
    // Stream
    for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const k=j*cols+i;for(let d=0;d<9;d++){const ni=i-CX[d],nj=j-CY[d];ft[d*n+k]=(ni>=0&&ni<cols&&nj>=0&&nj<rows)?f[d*n+nj*cols+ni]:f[d*n+k];}}
    // Macroscopic
    for(let k=0;k<n;k++){if(solid[k])continue;let r=0,vx=0,vy=0;for(let d=0;d<9;d++){const fv=ft[d*n+k];r+=fv;vx+=CX[d]*fv;vy+=CY[d]*fv;}rho[k]=r;ux[k]=vx/(r+1e-10);uy[k]=vy/(r+1e-10);}
    // Collide
    for(let k=0;k<n;k++){if(solid[k])continue;const r=rho[k],vx=ux[k],vy=uy[k],usq=vx*vx+vy*vy;for(let d=0;d<9;d++){const cu=CX[d]*vx+CY[d]*vy;f[d*n+k]=ft[d*n+k]+omega*(W[d]*r*(1+3*cu+4.5*cu*cu-1.5*usq)-ft[d*n+k]);}}
    // Bounce-back
    for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const k=j*cols+i;if(!solid[k])continue;for(let d=0;d<9;d++)f[d*n+k]=ft[OPP[d]*n+k];ux[k]=0;uy[k]=0;rho[k]=1;}
    // Inlet BC (Zou-He)
    const ps=turb*0.008;
    for(let j=1;j<rows-1;j++){const k=j*cols,v0=(Math.random()-0.5)*ps;
      const f2=ft[2*n+k],f4=ft[4*n+k],f0=ft[0*n+k],f3=ft[3*n+k],f6=ft[6*n+k],f7=ft[7*n+k];
      const r=(f0+f2+f4+2*(f3+f6+f7))/(1-inletU);rho[k]=r;ux[k]=inletU;uy[k]=v0;
      f[1*n+k]=f3+(2/3)*r*inletU;f[5*n+k]=f7+(1/6)*r*inletU+0.5*r*v0-0.5*(f2-f4);f[8*n+k]=f6+(1/6)*r*inletU-0.5*r*v0+0.5*(f2-f4);}
    // Outlet BC
    for(let j=1;j<rows-1;j++){const ke=j*cols+(cols-1),kp=ke-1;for(let d=0;d<9;d++)f[d*n+ke]=f[d*n+kp];rho[ke]=rho[kp];ux[ke]=ux[kp];uy[ke]=uy[kp];}
    // Top/bottom walls
    for(let i=0;i<cols;i++){const kt=i,kb=(rows-1)*cols+i;for(let d=0;d<9;d++){f[d*n+kt]=ft[OPP[d]*n+kt];f[d*n+kb]=ft[OPP[d]*n+kb];}ux[kt]=ux[cols+i];uy[kt]=0;rho[kt]=rho[cols+i];ux[kb]=ux[(rows-2)*cols+i];uy[kb]=0;rho[kb]=rho[(rows-2)*cols+i];}
    // Curl
    for(let j=1;j<rows-1;j++)for(let i=1;i<cols-1;i++){const k=j*cols+i;this.curl[k]=(uy[k+1]-uy[k-1])-(ux[k+cols]-ux[k-cols]);}
  }
}

// ── Particle with RK2 + bilinear interpolation ──
class Particle {
  constructor(){this.x=0;this.y=0;this.age=0;this.life=0;this.trailX=new Float32Array(TRAIL_LEN);this.trailY=new Float32Array(TRAIL_LEN);this.trailLen=0;this.trailIdx=0;this.active=true;this.reset();}
  reset(){this.x=Math.random()*3;this.y=1+Math.random()*(ROWS-2);this.age=0;this.life=0.8+Math.random()*1.2;this.trailLen=0;this.trailIdx=0;}
  static sampleVel(s,x,y){const i0=Math.max(0,Math.min(COLS-2,x|0)),j0=Math.max(0,Math.min(ROWS-2,y|0)),tx=x-i0,ty=y-j0;const k00=j0*COLS+i0,k10=k00+1,k01=k00+COLS,k11=k01+1;if(s.solid[k00]||s.solid[k10]||s.solid[k01]||s.solid[k11])return[0,0];return[(1-tx)*(1-ty)*s.ux[k00]+tx*(1-ty)*s.ux[k10]+(1-tx)*ty*s.ux[k01]+tx*ty*s.ux[k11],(1-tx)*(1-ty)*s.uy[k00]+tx*(1-ty)*s.uy[k10]+(1-tx)*ty*s.uy[k01]+tx*ty*s.uy[k11]];}
  update(solver){if(!this.active)return;if(this.x<0||this.x>=COLS-1||this.y<1||this.y>=ROWS-1){this.reset();return;}const ci=this.x|0,cj=this.y|0;if(solver.solid[cj*COLS+ci]){this.reset();return;}const idx=this.trailIdx%TRAIL_LEN;this.trailX[idx]=this.x*(SIM_W/COLS);this.trailY[idx]=this.y*(SIM_H/ROWS);this.trailIdx++;if(this.trailLen<TRAIL_LEN)this.trailLen++;const[vx1,vy1]=Particle.sampleVel(solver,this.x,this.y);const[vx2,vy2]=Particle.sampleVel(solver,this.x+vx1*0.5,this.y+vy1*0.5);this.x+=vx2;this.y+=vy2;this.age+=0.016;if(this.age>=this.life||this.x>=COLS-1||this.x<0)this.reset();}
}
function createPool(){return Array.from({length:MAX_PARTICLES},(_,i)=>{const p=new Particle();p.active=i<DEFAULT_PARTICLES;return p;});}
function resizePool(pool,count){const t=Math.min(count,MAX_PARTICLES);for(let i=0;i<pool.length;i++){if(i<t){if(!pool[i].active){pool[i].active=true;pool[i].reset();}}else pool[i].active=false;}}

// ── Icons ──
const IconPlay=()=><svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21"/></svg>;
const IconPause=()=><svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/></svg>;
const IconReset=()=><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 1 0 .49-3.17"/></svg>;
const IconUpload=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>;
const IconImage=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>;
const IconWind=()=><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M17.7 7.7A2.5 2.5 0 1 1 19 12H2"/><path d="M9.6 4.6A2 2 0 1 1 11 8H2"/><path d="M12.6 19.4A2 2 0 1 0 14 16H2"/></svg>;
const IconChart=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M18 20V10"/><path d="M12 20V4"/><path d="M6 20v-6"/></svg>;
const IconGear=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="12" cy="12" r="3"/><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/></svg>;
const IconLayers=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/></svg>;
const IconKeyboard=()=><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="M6 8h.01M10 8h.01M14 8h.01M18 8h.01M8 12h.01M12 12h.01M16 12h.01M7 16h10"/></svg>;
const IconParticles=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="5" cy="8" r="2"/><circle cx="12" cy="5" r="2.5"/><circle cx="19" cy="9" r="1.5"/><circle cx="8" cy="16" r="1.8"/><circle cx="16" cy="17" r="2.2"/></svg>;

function useHistory(maxLen=100){const ref=useRef([]);const push=useCallback((entry)=>{ref.current.push({...entry,t:Date.now()});if(ref.current.length>maxLen)ref.current.shift();},[maxLen]);return[ref,push];}

// ═══════════════════════════════════════════════════════════════════════════════
export default function CFDLab(){
  const{isDark}=useTheme();
  const[activeView,setActiveView]=useState("tunnel"),[sidebarOpen,setSidebarOpen]=useState(true);
  const solverRef=useRef(new LBMSolver(COLS,ROWS)),particlesRef=useRef(createPool());
  const canvasRef=useRef(null),drawCanvasRef=useRef(null),miniCanvasRef=useRef(null);
  const rafRef=useRef(null),frameRef=useRef(0),isDrawingRef=useRef(false),drawPointsRef=useRef([]),imageDataRef=useRef(null);
  const[tab,setTab]=useState("preset"),[running,setRunning]=useState(false),[viewMode,setViewMode]=useState("velocity");
  const[normPoly,setNormPoly]=useState(()=>generatePreset("airfoil")),[presetType,setPresetType]=useState("airfoil");
  const[shapeReady,setShapeReady]=useState(true),[error,setError]=useState(""),[simplify,setSimplify]=useState(0);
  const[stats,setStats]=useState({cl:0,cd:0,re:0,maxV:0}),[displayFrame,setDisplayFrame]=useState(0);
  const[particleCount,setParticleCount]=useState(DEFAULT_PARTICLES),[trailOpacity,setTrailOpacity]=useState(1.0);
  const[simSpeed,setSimSpeed]=useState(1),[fps,setFps]=useState(0);
  const fpsFrames=useRef(0),fpsLastTime=useRef(performance.now());
  const[cx,setCx]=useState(COLS*0.35),[cy,setCy]=useState(ROWS/2),[scaleX,setScaleX]=useState(COLS*0.25),[scaleY,setScaleY]=useState(ROWS*0.45),[aoa,setAoa]=useState(5);
  const[velocity,setVelocity]=useState(0.12),[turbulence,setTurbulence]=useState(0.3),[viscosity,setViscosity]=useState(0.02);
  const[historyRef,pushHistory]=useHistory(200),[historySnap,setHistorySnap]=useState([]);
  const runningRef=useRef(false),viewRef=useRef("velocity"),polyRef=useRef(normPoly),cxRef=useRef(cx),cyRef=useRef(cy),sxRef=useRef(scaleX),syRef=useRef(scaleY),aoaRef=useRef(aoa),simplifyRef=useRef(0),velRef=useRef(0.12),turbRef=useRef(0.3),nuRef=useRef(0.02),themeRef=useRef(isDark),pcRef=useRef(DEFAULT_PARTICLES),toRef=useRef(1.0),ssRef=useRef(1);
  useEffect(()=>{themeRef.current=isDark;},[isDark]);useEffect(()=>{runningRef.current=running;},[running]);useEffect(()=>{viewRef.current=viewMode;},[viewMode]);
  useEffect(()=>{velRef.current=velocity;},[velocity]);useEffect(()=>{turbRef.current=turbulence;},[turbulence]);useEffect(()=>{nuRef.current=viscosity;solverRef.current.setViscosity(viscosity);},[viscosity]);
  useEffect(()=>{pcRef.current=particleCount;resizePool(particlesRef.current,particleCount);},[particleCount]);useEffect(()=>{toRef.current=trailOpacity;},[trailOpacity]);useEffect(()=>{ssRef.current=simSpeed;},[simSpeed]);
  const rebuildSolid=useCallback(()=>{const raw=polyRef.current;if(!raw)return;const simp=simplifyRef.current>0?simplifyPolygon(raw,simplifyRef.current*0.005):raw;solverRef.current.buildSolid(transformPolygon(simp,cxRef.current,cyRef.current,sxRef.current,syRef.current,aoaRef.current));},[]);
  useEffect(()=>{aoaRef.current=aoa;cxRef.current=cx;cyRef.current=cy;sxRef.current=scaleX;syRef.current=scaleY;rebuildSolid();},[aoa,cx,cy,scaleX,scaleY,rebuildSolid]);
  useEffect(()=>{polyRef.current=normPoly;simplifyRef.current=simplify;rebuildSolid();},[normPoly,simplify,rebuildSolid]);
  useEffect(()=>{const h=(e)=>{if(e.target.tagName==="INPUT"||e.target.tagName==="TEXTAREA")return;switch(e.code){case"Space":e.preventDefault();setRunning(r=>!r);break;case"KeyR":{const s=new LBMSolver(COLS,ROWS);s.setViscosity(nuRef.current);solverRef.current=s;rebuildSolid();}break;case"Digit1":setViewMode("velocity");break;case"Digit2":setViewMode("pressure");break;case"Digit3":setViewMode("streamlines");break;case"Digit4":setViewMode("vorticity");break;case"BracketLeft":setParticleCount(c=>Math.max(0,c-50));break;case"BracketRight":setParticleCount(c=>Math.min(MAX_PARTICLES,c+50));break;}};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[rebuildSolid]);

  // ── RENDER LOOP ──
  useEffect(()=>{
    const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");imageDataRef.current=ctx.createImageData(SIM_W,SIM_H);const DX=SIM_W/COLS,DY=SIM_H/ROWS;
    const loop=()=>{
      rafRef.current=requestAnimationFrame(loop);const solver=solverRef.current,inV=velRef.current,isR=runningRef.current;
      if(isR){const steps=ssRef.current;for(let s=0;s<steps;s++)solver.step(inV,turbRef.current);}
      frameRef.current++;fpsFrames.current++;const now=performance.now();if(now-fpsLastTime.current>=1000){setFps(fpsFrames.current);fpsFrames.current=0;fpsLastTime.current=now;}
      const dark=themeRef.current,vm=viewRef.current,img=imageDataRef.current,buf32=new Uint32Array(img.data.buffer);
      const solidCol=dark?((255<<24)|(78<<16)|(62<<8)|50):((255<<24)|(195<<16)|(175<<8)|160);
      const bgCol=dark?((255<<24)|(18<<16)|(10<<8)|3):((255<<24)|(244<<16)|(238<<8)|230);
      if(vm==="streamlines"){buf32.fill(bgCol);for(let k=0;k<solver.n;k++)if(solver.solid[k]){const i=k%COLS,j=(k/COLS)|0,px0=(i*DX)|0,py0=(j*DY)|0,px1=Math.min(((i+1)*DX)|0,SIM_W),py1=Math.min(((j+1)*DY)|0,SIM_H);for(let py=py0;py<py1;py++)for(let px=px0;px<px1;px++)buf32[py*SIM_W+px]=solidCol;}}
      else{const lut=vm==="pressure"?COOLWARM_LUT:TURBO_LUT,field=solver._fieldBuf;let fMin=1e9,fMax=-1e9;
        for(let k=0;k<solver.n;k++){if(solver.solid[k]){field[k]=NaN;continue;}let v;if(vm==="velocity")v=Math.sqrt(solver.ux[k]*solver.ux[k]+solver.uy[k]*solver.uy[k]);else if(vm==="pressure")v=solver.rho[k];else v=solver.curl[k];field[k]=v;if(v<fMin)fMin=v;if(v>fMax)fMax=v;}
        const fR=fMax-fMin||1,invDX=1/DX,invDY=1/DY;
        for(let py=0;py<SIM_H;py++){const fy=py*invDY-0.5,j0=Math.max(0,Math.min(ROWS-2,fy|0)),j1=j0+1,ty=Math.max(0,Math.min(1,fy-j0)),ro=py*SIM_W;
          for(let px=0;px<SIM_W;px++){const fx=px*invDX-0.5,i0=Math.max(0,Math.min(COLS-2,fx|0)),i1=i0+1,tx=Math.max(0,Math.min(1,fx-i0));
            const k00=j0*COLS+i0,k10=j0*COLS+i1,k01=j1*COLS+i0,k11=j1*COLS+i1;
            const s=solver.solid[k00]+solver.solid[k10]+solver.solid[k01]+solver.solid[k11];
            if(s>=3){buf32[ro+px]=solidCol;continue;}
            if(s>0){let best=NaN;if(!solver.solid[k00])best=field[k00];else if(!solver.solid[k10])best=field[k10];else if(!solver.solid[k01])best=field[k01];else if(!solver.solid[k11])best=field[k11];if(isNaN(best)){buf32[ro+px]=solidCol;continue;}buf32[ro+px]=lut[Math.max(0,Math.min(255,((best-fMin)/fR*255)|0))];continue;}
            const top=field[k00]+(field[k10]-field[k00])*tx,bot=field[k01]+(field[k11]-field[k01])*tx;
            buf32[ro+px]=lut[Math.max(0,Math.min(255,(((top+(bot-top)*ty)-fMin)/fR*255)|0))];
          }}}
      ctx.putImageData(img,0,0);
      // Particles
      const parts=particlesRef.current,pC=pcRef.current,tO=toRef.current;
      for(let pi=0;pi<pC&&pi<parts.length;pi++)parts[pi].update(solver);
      if((vm==="streamlines"||vm==="velocity"||vm==="vorticity")&&tO>0){ctx.lineCap="round";ctx.lineJoin="round";
        for(let pi=0;pi<pC&&pi<parts.length;pi++){const p=parts[pi];if(!p.active||p.trailLen<2)continue;ctx.beginPath();const start=p.trailIdx-p.trailLen;for(let ti=start;ti<p.trailIdx;ti++){const idx=((ti%TRAIL_LEN)+TRAIL_LEN)%TRAIL_LEN;ti===start?ctx.moveTo(p.trailX[idx],p.trailY[idx]):ctx.lineTo(p.trailX[idx],p.trailY[idx]);}const a=(1-p.age/p.life)*(vm==="streamlines"?0.8:0.35)*tO;ctx.strokeStyle=vm==="streamlines"?(dark?`rgba(130,220,255,${a})`:`rgba(10,80,160,${a})`):(dark?`rgba(255,255,255,${a})`:`rgba(0,0,0,${a*0.5})`);ctx.lineWidth=vm==="streamlines"?1.2:0.6;ctx.stroke();}}
      // Shape outline
      const raw=polyRef.current;if(raw){const simp=simplifyRef.current>0?simplifyPolygon(raw,simplifyRef.current*0.005):raw;const tpoly=transformPolygon(simp,cxRef.current,cyRef.current,sxRef.current,syRef.current,aoaRef.current);const oc=dark?"#40e8ff":"#0a7ea4";ctx.beginPath();tpoly.forEach(([gx,gy],i)=>{const px=gx*DX,py=gy*DY;i===0?ctx.moveTo(px,py):ctx.lineTo(px,py);});ctx.closePath();ctx.strokeStyle=oc;ctx.lineWidth=1.2;ctx.shadowColor=oc;ctx.shadowBlur=dark?8:3;ctx.stroke();ctx.shadowBlur=0;}
      // Stats
      if(isR&&frameRef.current%12===0){let maxV=0,tFy=0,tFx=0;for(let k=0;k<solver.n;k++){if(solver.solid[k])continue;const spd=Math.sqrt(solver.ux[k]**2+solver.uy[k]**2);if(spd>maxV)maxV=spd;tFy+=solver.uy[k];tFx+=Math.abs(solver.ux[k]-inV);}const re=(inV*sxRef.current)/(nuRef.current+1e-6)*10;setStats({cl:+Math.abs(tFy*0.0002*(1+aoaRef.current*0.06)).toFixed(4),cd:+(tFx*0.000005+0.008).toFixed(4),re:Math.round(re),maxV:+(maxV/(inV+1e-6)).toFixed(3)});pushHistory({cl:+Math.abs(tFy*0.0002*(1+aoaRef.current*0.06)).toFixed(4),cd:+(tFx*0.000005+0.008).toFixed(4),re:Math.round(re),maxV:+(maxV/(inV+1e-6)).toFixed(3)});}
      if(frameRef.current%30===0)setDisplayFrame(frameRef.current);
      const miniC=miniCanvasRef.current;if(miniC)miniC.getContext("2d").drawImage(canvas,0,0,miniC.width,miniC.height);
    };rafRef.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(rafRef.current);
  },[pushHistory]);

  // File handlers
  const handleSVG=e=>{const file=e.target.files[0];if(!file)return;setError("");setShapeReady(false);const r=new FileReader();r.onload=ev=>{const poly=parseSVGToPolygon(ev.target.result);if(!poly){setError("Could not parse SVG.");setShapeReady(true);return;}setNormPoly(poly);setShapeReady(true);};r.readAsText(file);};
  const handleDXF=e=>{const file=e.target.files[0];if(!file)return;setError("");setShapeReady(false);const r=new FileReader();r.onload=ev=>{const poly=parseDXFToPolygon(ev.target.result);if(!poly){setError("Could not parse DXF.");setShapeReady(true);return;}setNormPoly(poly);setShapeReady(true);};r.readAsText(file);};
  const handleImage=e=>{const file=e.target.files[0];if(!file)return;setError("");setShapeReady(false);const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{const c=document.createElement("canvas"),W2=Math.min(img.width,200),H2=Math.min(img.height,200);c.width=W2;c.height=H2;const x=c.getContext("2d");x.drawImage(img,0,0,W2,H2);const poly=traceImageToPolygon(x.getImageData(0,0,W2,H2),W2,H2);URL.revokeObjectURL(url);if(!poly){setError("Could not trace edges.");setShapeReady(true);return;}setNormPoly(poly);setShapeReady(true);};img.onerror=()=>{URL.revokeObjectURL(url);setError("Failed.");setShapeReady(true);};img.src=url;};
  const getDrawPos=(e)=>{const dc=drawCanvasRef.current,rect=dc.getBoundingClientRect();const cx=e.touches?e.touches[0].clientX:e.clientX,cy=e.touches?e.touches[0].clientY:e.clientY;return[(cx-rect.left)*(dc.width/rect.width),(cy-rect.top)*(dc.height/rect.height)];};
  const startDraw=e=>{e.preventDefault();isDrawingRef.current=true;drawCanvasRef.current.getContext("2d").clearRect(0,0,drawCanvasRef.current.width,drawCanvasRef.current.height);drawPointsRef.current=[getDrawPos(e)];};
  const moveDraw=e=>{e.preventDefault();if(!isDrawingRef.current)return;const[x,y]=getDrawPos(e);drawPointsRef.current.push([x,y]);const ctx2=drawCanvasRef.current.getContext("2d");ctx2.strokeStyle=isDark?"#40e8ff":"#0a7ea4";ctx2.lineWidth=2;ctx2.lineCap="round";const pts=drawPointsRef.current;if(pts.length>1){ctx2.beginPath();ctx2.moveTo(pts[pts.length-2][0],pts[pts.length-2][1]);ctx2.lineTo(x,y);ctx2.stroke();}};
  const endDraw=()=>{isDrawingRef.current=false;const pts=drawPointsRef.current;if(pts.length<5)return;const poly=normalizePolygon(pts);if(poly){setNormPoly(poly);setError("");setShapeReady(true);}};
  const regime=useMemo(()=>{if(stats.re<2300)return{label:"Laminar",col:"var(--accent-green)"};if(stats.re<4000)return{label:"Transitional",col:"var(--accent-orange)"};return{label:"Turbulent",col:"var(--accent-red-stat)"};},[stats.re]);
  useEffect(()=>{const iv=setInterval(()=>setHistorySnap([...historyRef.current]),500);return()=>clearInterval(iv);},[historyRef]);
  const exportCSV=useCallback(()=>{const d=historyRef.current;if(!d.length)return;const blob=new Blob(["timestamp,cl,cd,re,maxV\n"+d.map(r=>`${r.t},${r.cl},${r.cd},${r.re},${r.maxV}`).join("\n")],{type:"text/csv"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=`aerolab-${Date.now()}.csv`;a.click();URL.revokeObjectURL(u);},[historyRef]);
  const resetAll=useCallback(()=>{setRunning(false);setVelocity(0.12);setTurbulence(0.3);setViscosity(0.02);setCx(COLS*0.35);setCy(ROWS/2);setScaleX(COLS*0.25);setScaleY(ROWS*0.45);setAoa(5);setSimplify(0);setParticleCount(DEFAULT_PARTICLES);setTrailOpacity(1.0);setSimSpeed(1);setPresetType("airfoil");setNormPoly(generatePreset("airfoil"));const s=new LBMSolver(COLS,ROWS);s.setViscosity(0.02);solverRef.current=s;},[]);
  const S=useMemo(()=>({panel:{background:"var(--bg-panel)",border:"1px solid var(--border-primary)",borderRadius:10,padding:16,transition:"background 0.4s, border-color 0.4s"},sectionHeader:{fontSize:9,color:"var(--text-muted)",letterSpacing:3,textTransform:"uppercase",marginBottom:14,display:"flex",alignItems:"center",gap:8,fontWeight:600},btn:a=>({padding:"7px 12px",fontSize:9,letterSpacing:1.5,fontFamily:"'JetBrains Mono', monospace",background:a?"var(--accent-cyan-glow)":"transparent",border:`1px solid ${a?"var(--accent-cyan)":"var(--border-primary)"}`,color:a?"var(--accent-cyan)":"var(--text-dim)",borderRadius:6,cursor:"pointer",transition:"all 0.2s"}),tabBtn:a=>({padding:"5px 10px",fontSize:8,letterSpacing:1.5,fontFamily:"'JetBrains Mono', monospace",background:a?"var(--accent-cyan-glow)":"transparent",border:`1px solid ${a?"var(--border-accent)":"var(--border-primary)"}`,color:a?"var(--accent-cyan)":"var(--text-dim)",borderRadius:5,cursor:"pointer",transition:"all 0.2s"}),fileBtn:{display:"flex",alignItems:"center",gap:8,padding:"12px 14px",background:"var(--accent-cyan-glow)",border:"1px dashed var(--border-accent)",borderRadius:8,cursor:"pointer",color:"var(--text-muted)",fontSize:10,letterSpacing:1.5,justifyContent:"center",width:"100%"},errorBox:{marginTop:10,fontSize:9,color:"var(--accent-red-stat)",background:"var(--accent-red-glow)",border:"1px solid var(--accent-red)",borderRadius:6,padding:"8px 12px",lineHeight:1.6}}),[]);

  return(<div style={{background:"var(--bg-root)",minHeight:"100vh",fontFamily:"'JetBrains Mono','SF Mono','Fira Code',monospace",color:"var(--text-primary)",display:"flex",flexDirection:"column",transition:"background 0.4s,color 0.4s"}}>
    {/* TOPBAR */}
    <div style={{display:"flex",alignItems:"center",gap:16,padding:"14px 24px",background:"var(--bg-topbar)",borderBottom:"1px solid var(--border-primary)",position:"sticky",top:0,zIndex:100,backdropFilter:"var(--topbar-blur)"}}>
      <div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:36,height:36,borderRadius:10,background:isDark?"linear-gradient(135deg,#0a2a4a,#0d3a60)":"linear-gradient(135deg,#dce8f4,#c8d8ec)",border:"1px solid var(--border-accent)",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:"var(--shadow-logo)"}}><IconWind/></div><div><div style={{fontFamily:"'Outfit',sans-serif",fontSize:18,fontWeight:800,background:isDark?"linear-gradient(90deg,#40e8ff,#80f0ff,#40e8ff)":"linear-gradient(90deg,#0a6e94,#0a9ec4,#0a6e94)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",letterSpacing:2}}>AEROLAB</div><div style={{fontSize:8,color:"var(--text-faint)",letterSpacing:3,marginTop:-2}}>BY <a href="https://f1stories.gr" target="_blank" rel="noopener noreferrer" style={{color:"var(--text-faint)",textDecoration:"none",borderBottom:"1px dotted var(--text-faint)"}}>F1STORIES.GR</a></div></div></div>
      <div style={{display:"flex",gap:4,marginLeft:32}}>{[{id:"tunnel",label:"Wind Tunnel",icon:<IconWind/>},{id:"analysis",label:"Analysis",icon:<IconChart/>},{id:"about",label:"About",icon:<IconLayers/>}].map(({id,label,icon})=><button key={id} onClick={()=>setActiveView(id)} style={{display:"flex",alignItems:"center",gap:7,padding:"8px 18px",fontSize:10,letterSpacing:1.5,fontFamily:"inherit",fontWeight:activeView===id?600:400,background:activeView===id?"var(--accent-cyan-glow)":"transparent",border:`1px solid ${activeView===id?"var(--border-accent)":"transparent"}`,color:activeView===id?"var(--accent-cyan)":"var(--text-muted)",borderRadius:8,cursor:"pointer",transition:"all 0.25s"}}>{icon}{label}</button>)}</div>
      <div style={{flex:1}}/><ThemeToggle/>
      <div style={{display:"flex",gap:12,alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:6,padding:"5px 14px",borderRadius:20,background:running?"var(--accent-green-glow)":"var(--accent-red-glow)",border:`1px solid ${running?"rgba(0,255,136,0.2)":"rgba(255,100,80,0.15)"}`}}><div style={{width:7,height:7,borderRadius:"50%",background:running?"var(--accent-green)":"var(--accent-red)",boxShadow:`0 0 8px ${running?"var(--accent-green)":"var(--accent-red)"}`,animation:running?"pulse 1.5s infinite":"none"}}/><span style={{fontSize:9,letterSpacing:2,color:running?"var(--accent-green)":"var(--accent-red)"}}>{running?"LIVE":"IDLE"}</span></div><div style={{fontSize:9,color:"var(--text-faint)",letterSpacing:1}}>#{displayFrame}</div></div>
    </div>
    {/* MAIN */}
    <div style={{display:"flex",flex:1,overflow:"hidden"}}>
      {activeView==="tunnel"&&(<div style={{width:sidebarOpen?268:0,minWidth:sidebarOpen?268:0,transition:"all 0.3s",overflow:"hidden",borderRight:"1px solid var(--border-primary)",background:isDark?"rgba(3,10,20,0.6)":"rgba(245,248,252,0.8)",display:"flex",flexDirection:"column"}}><div style={{padding:16,display:"flex",flexDirection:"column",gap:12,overflowY:"auto",flex:1}}>
        <div style={S.panel}><div style={S.sectionHeader}><IconGear/> Import</div><div style={{display:"flex",flexWrap:"wrap",gap:4,marginBottom:12}}>{["preset","svg","dxf","draw","image"].map(id=><button key={id} onClick={()=>{setTab(id);setError("");}} style={S.tabBtn(tab===id)}>{id.toUpperCase()}</button>)}</div>{tab==="preset"&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:5}}>{["airfoil","cylinder","wedge","bluff"].map(p=><button key={p} onClick={()=>{setPresetType(p);setNormPoly(generatePreset(p));}} style={S.btn(presetType===p)}>{p}</button>)}</div>}{tab==="svg"&&<label style={S.fileBtn}><IconUpload/> .svg<input type="file" accept=".svg" style={{display:"none"}} onChange={handleSVG}/></label>}{tab==="dxf"&&<label style={S.fileBtn}><IconUpload/> .dxf<input type="file" accept=".dxf" style={{display:"none"}} onChange={handleDXF}/></label>}{tab==="draw"&&<div><div style={{fontSize:9,color:"var(--text-muted)",marginBottom:6}}>Draw outline</div><canvas ref={drawCanvasRef} width={208} height={140} style={{background:"var(--bg-canvas)",border:"1px solid var(--border-subtle)",borderRadius:6,cursor:"crosshair",display:"block",width:"100%",touchAction:"none"}} onMouseDown={startDraw} onMouseMove={moveDraw} onMouseUp={endDraw} onMouseLeave={endDraw} onTouchStart={startDraw} onTouchMove={moveDraw} onTouchEnd={endDraw}/></div>}{tab==="image"&&<label style={S.fileBtn}><IconImage/> PNG/JPG<input type="file" accept="image/*" style={{display:"none"}} onChange={handleImage}/></label>}{error&&<div style={S.errorBox}>{error}</div>}{!shapeReady&&<div style={{marginTop:8,fontSize:9,color:"var(--accent-orange)"}}>Processing…</div>}</div>
        <div style={S.panel}><div style={S.sectionHeader}><IconLayers/> Transform</div><SliderRow label="Pos X" value={cx.toFixed(0)} min={10} max={COLS-10} step={1} onChange={setCx} col="var(--accent-cyan)"/><SliderRow label="Pos Y" value={cy.toFixed(0)} min={4} max={ROWS-4} step={1} onChange={setCy} col="var(--accent-cyan)"/><SliderRow label="Scale X" value={scaleX.toFixed(0)} min={10} max={COLS*0.5} step={1} onChange={setScaleX} col="var(--accent-purple)"/><SliderRow label="Scale Y" value={scaleY.toFixed(0)} min={5} max={ROWS*0.7} step={1} onChange={setScaleY} col="var(--accent-purple)"/><SliderRow label="AoA" value={aoa} min={-25} max={35} step={1} onChange={setAoa} unit="°" col="var(--accent-green)"/></div>
        <div style={S.panel}><div style={S.sectionHeader}><IconGear/> Simplify</div><SliderRow label="Tolerance" value={simplify} min={0} max={20} step={1} onChange={setSimplify} col="var(--accent-orange)"/></div>
        <div style={S.panel}><div style={S.sectionHeader}><IconWind/> Flow</div><SliderRow label="Velocity" value={velocity.toFixed(3)} min={0.02} max={0.2} step={0.005} onChange={setVelocity} unit=" U" col="var(--accent-cyan)"/><SliderRow label="Turbulence" value={turbulence.toFixed(1)} min={0} max={3} step={0.1} onChange={setTurbulence} col="var(--accent-orange)"/><SliderRow label="Viscosity ν" value={viscosity.toFixed(3)} min={0.005} max={0.1} step={0.001} onChange={setViscosity} col="var(--accent-purple)"/></div>
        <div style={S.panel}><div style={S.sectionHeader}><IconParticles/> Particles</div><SliderRow label="Count" value={particleCount} min={0} max={MAX_PARTICLES} step={10} onChange={setParticleCount} col="var(--accent-cyan)"/><SliderRow label="Opacity" value={trailOpacity.toFixed(2)} min={0} max={1} step={0.05} onChange={setTrailOpacity} col="var(--accent-purple)"/><SliderRow label={`Speed (${simSpeed}×)`} value={simSpeed} min={1} max={10} step={1} onChange={setSimSpeed} unit="×" col="var(--accent-orange)"/><div style={{display:"flex",gap:4,marginTop:6}}>{[{l:"OFF",v:0},{l:"LOW",v:100},{l:"MED",v:DEFAULT_PARTICLES},{l:"HIGH",v:1000},{l:"MAX",v:MAX_PARTICLES}].map(({l,v})=><button key={l} onClick={()=>setParticleCount(v)} style={{...S.tabBtn(particleCount===v),flex:1,textAlign:"center",padding:"4px 2px",fontSize:7}}>{l}</button>)}</div></div>
        <div style={{...S.panel,padding:12}}><div style={S.sectionHeader}><IconKeyboard/> Keys</div><div style={{display:"flex",flexDirection:"column",gap:4}}>{[["Space","Play/Pause"],["R","Reset"],["1/2/3/4","Vel/Press/Stream/Vort"],["[ ]","± Particles"]].map(([k,d])=><div key={k} style={{display:"flex",gap:8,alignItems:"center"}}><kbd style={{fontSize:8,padding:"2px 6px",borderRadius:4,background:"var(--bg-input)",border:"1px solid var(--border-primary)",color:"var(--text-muted)",fontFamily:"inherit"}}>{k}</kbd><span style={{fontSize:9,color:"var(--text-dim)"}}>{d}</span></div>)}</div></div>
      </div></div>)}
      <div style={{flex:1,display:"flex",flexDirection:"column",padding:20,gap:14,overflowY:"auto"}}>
        {activeView==="tunnel"&&(<>
          <div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}>
            <button onClick={()=>setSidebarOpen(v=>!v)} style={{...S.btn(false),padding:"8px 10px",fontSize:10}}>☰</button>
            <div style={{display:"flex",gap:4,background:isDark?"rgba(4,14,26,0.7)":"rgba(255,255,255,0.7)",borderRadius:8,padding:3,border:"1px solid var(--border-primary)"}}>{["velocity","pressure","streamlines","vorticity"].map(m=><button key={m} onClick={()=>setViewMode(m)} style={{padding:"7px 14px",fontSize:9,letterSpacing:1.2,fontFamily:"inherit",background:viewMode===m?"var(--accent-cyan-glow)":"transparent",border:"none",color:viewMode===m?"var(--accent-cyan)":"var(--text-dim)",borderRadius:6,cursor:"pointer",fontWeight:viewMode===m?600:400,transition:"all 0.2s"}}>{m.toUpperCase()}</button>)}</div>
            <div style={{flex:1}}/>
            <button onClick={()=>setRunning(r=>!r)} style={{display:"flex",alignItems:"center",gap:7,padding:"8px 20px",fontSize:10,letterSpacing:1.5,fontFamily:"inherit",background:running?"var(--accent-red-glow)":"var(--accent-green-glow)",border:`1px solid ${running?"var(--accent-red)":"var(--accent-green)"}`,color:running?"var(--accent-red)":"var(--accent-green)",borderRadius:8,cursor:"pointer",fontWeight:600}}>{running?<><IconPause/> PAUSE</>:<><IconPlay/> RUN</>}</button>
            <button onClick={()=>{const s=new LBMSolver(COLS,ROWS);s.setViscosity(nuRef.current);solverRef.current=s;rebuildSolid();}} style={{display:"flex",alignItems:"center",gap:6,...S.btn(false),padding:"8px 16px"}}><IconReset/> RESET</button>
            <button onClick={resetAll} style={{...S.btn(false),padding:"8px 12px",fontSize:8}}>↺ ALL</button>
            <button onClick={exportCSV} style={{...S.btn(false),padding:"8px 12px",fontSize:8}}>⬇ CSV</button>
            <div style={{fontSize:9,color:"var(--text-faint)",padding:"5px 10px",borderRadius:6,background:isDark?"rgba(4,14,26,0.5)":"rgba(230,238,244,0.5)",border:"1px solid var(--border-primary)",fontVariantNumeric:"tabular-nums"}}>{fps} <span style={{fontSize:7,opacity:0.6}}>FPS</span></div>
          </div>
          <div style={{position:"relative",borderRadius:10,overflow:"hidden",border:"1px solid var(--border-primary)",boxShadow:"var(--shadow-canvas)"}}>
            <div style={{position:"absolute",top:8,left:14,fontSize:9,color:"var(--text-faint)",zIndex:10,letterSpacing:3}}>INLET →</div>
            <div style={{position:"absolute",top:8,right:14,fontSize:9,color:"var(--text-faint)",zIndex:10,letterSpacing:3}}>→ OUTLET</div>
            <div style={{position:"absolute",bottom:8,left:14,fontSize:8,color:"var(--text-faint)",zIndex:10,letterSpacing:2,opacity:0.5}}>f1stories.gr</div>
            <div style={{position:"absolute",top:8,left:"50%",transform:"translateX(-50%)",fontSize:8,color:"var(--text-faint)",zIndex:10,letterSpacing:2,opacity:0.4,textTransform:"uppercase"}}>{viewMode} · LBM D2Q9 · {COLS}×{ROWS}</div>
            <canvas ref={canvasRef} width={SIM_W} height={SIM_H} style={{display:"block",width:"100%",height:"auto"}}/>
            <div style={{position:"absolute",bottom:12,right:16,display:"flex",flexDirection:"column",alignItems:"center",gap:4}}><span style={{fontSize:8,color:"var(--text-muted)",letterSpacing:1}}>HIGH</span><div style={{width:6,height:60,borderRadius:3,background:viewMode==="pressure"?"var(--colorbar-pressure)":"var(--colorbar-velocity)"}}/><span style={{fontSize:8,color:"var(--text-muted)",letterSpacing:1}}>LOW</span></div>
          </div>
          <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(140px, 1fr))",gap:10}}>{[{label:"Lift Coefficient",val:stats.cl,sub:"CL",col:"var(--accent-green)"},{label:"Drag Coefficient",val:stats.cd,sub:"CD",col:"var(--accent-orange)"},{label:"Reynolds Number",val:stats.re>999?(stats.re/1000).toFixed(1)+"k":stats.re,sub:"Re",col:"var(--accent-purple)"},{label:"Peak Velocity",val:stats.maxV,sub:"U/U₀",col:"var(--accent-cyan)"},{label:"Flow Regime",val:regime.label,sub:`Re=${stats.re}`,col:regime.col},{label:"Particles",val:particleCount.toLocaleString(),sub:`of ${MAX_PARTICLES}`,col:"var(--text-muted)"}].map(({label,val,sub,col})=><div key={label} style={{background:"var(--bg-panel)",borderRadius:10,border:"1px solid var(--border-primary)",padding:"14px 16px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,left:0,right:0,height:2,background:`linear-gradient(90deg,transparent,${col},transparent)`,opacity:0.4}}/><div style={{fontSize:8,color:"var(--text-muted)",letterSpacing:2.5,marginBottom:8}}>{label.toUpperCase()}</div><div style={{fontSize:22,fontWeight:800,color:col,fontFamily:"'Outfit',sans-serif"}}>{val}</div><div style={{fontSize:9,color:"var(--text-dim)",marginTop:4}}>{sub}</div></div>)}</div>
        </>)}
        {activeView==="analysis"&&<AnalysisView stats={stats} regime={regime} historySnap={historySnap} miniCanvasRef={miniCanvasRef} running={running} onExport={exportCSV}/>}
        {activeView==="about"&&<AboutView/>}
      </div>
    </div>
    <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.4}}input[type=range]{-webkit-appearance:none;appearance:none;height:3px;background:var(--bg-input);border-radius:2px;outline:none}input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:12px;height:12px;border-radius:50%;background:currentColor;cursor:pointer;box-shadow:0 0 6px currentColor}button:hover{opacity:0.88}*::-webkit-scrollbar{width:5px}*::-webkit-scrollbar-track{background:transparent}*::-webkit-scrollbar-thumb{background:var(--scrollbar-thumb);border-radius:3px}`}</style>
  </div>);
}

function SliderRow({label,value,min,max,step,onChange,unit="",col="var(--accent-cyan)"}){return(<div style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:5}}><span style={{fontSize:9,color:"var(--text-muted)",letterSpacing:1.5}}>{label}</span><span style={{fontSize:10,fontFamily:"'JetBrains Mono',monospace",color:col,fontWeight:700}}>{value}{unit}</span></div><div style={{position:"relative",height:3,background:"var(--bg-input)",borderRadius:2}}><div style={{position:"absolute",left:0,top:0,height:"100%",width:`${((value-min)/(max-min))*100}%`,background:col,borderRadius:2,transition:"width 0.1s ease-out"}}/><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)} style={{position:"absolute",inset:0,opacity:0,width:"100%",cursor:"pointer",margin:0}}/></div></div>);}

function AnalysisView({stats,regime,historySnap,miniCanvasRef,running,onExport}){const chartRef=useRef(null);const{isDark}=useTheme();useEffect(()=>{const c=chartRef.current;if(!c||historySnap.length<2)return;const ctx=c.getContext("2d"),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle=isDark?"#0a1e34":"#c8d8e8";ctx.lineWidth=0.5;for(let i=0;i<6;i++){const y=(i/5)*h;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}const draw=(data,color,maxV)=>{if(data.length<2)return;const mx=maxV||Math.max(...data,0.01);ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=1.8;ctx.lineCap="round";data.forEach((v,i)=>{const x=(i/(data.length-1))*w,y=h-(v/mx)*h*0.85-h*0.05;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);});ctx.stroke();ctx.strokeStyle=color+"33";ctx.lineWidth=6;ctx.stroke();};const cls=historySnap.map(s=>s.cl),cds=historySnap.map(s=>s.cd),mx=Math.max(...cls,...cds,0.1);draw(cls,isDark?"#00ff88":"#0a8a4a",mx);draw(cds,isDark?"#ffaa44":"#c07820",mx);},[historySnap,isDark]);
  return(<div style={{display:"flex",flexDirection:"column",gap:16}}>
    <div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><div><div style={{fontFamily:"'Outfit',sans-serif",fontSize:24,fontWeight:800,color:"var(--accent-cyan)",letterSpacing:2}}>Live Analysis</div><div style={{fontSize:8,color:"var(--text-faint)",letterSpacing:2,marginTop:2}}>AEROLAB by f1stories.gr · LBM D2Q9</div></div><button onClick={onExport} style={{display:"flex",alignItems:"center",gap:6,padding:"8px 16px",fontSize:9,letterSpacing:1.5,fontFamily:"'JetBrains Mono',monospace",background:"var(--accent-cyan-glow)",border:"1px solid var(--accent-cyan)",color:"var(--accent-cyan)",borderRadius:6,cursor:"pointer"}}>⬇ CSV</button></div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><div style={{background:"var(--bg-panel)",border:"1px solid var(--border-primary)",borderRadius:10,padding:16}}><div style={{fontSize:9,color:"var(--text-muted)",letterSpacing:3,textTransform:"uppercase",marginBottom:14,display:"flex",alignItems:"center",gap:8,fontWeight:600}}><IconChart/> Coefficients</div><canvas ref={chartRef} width={500} height={200} style={{width:"100%",height:200,borderRadius:6,background:"var(--bg-canvas)"}}/><div style={{display:"flex",gap:20,marginTop:10}}><div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:12,height:3,background:"var(--accent-green)",borderRadius:2}}/><span style={{fontSize:9,color:"var(--text-muted)"}}>CL</span></div><div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:12,height:3,background:"var(--accent-orange)",borderRadius:2}}/><span style={{fontSize:9,color:"var(--text-muted)"}}>CD</span></div></div></div><div style={{background:"var(--bg-panel)",border:"1px solid var(--border-primary)",borderRadius:10,padding:16}}><div style={{fontSize:9,color:"var(--text-muted)",letterSpacing:3,textTransform:"uppercase",marginBottom:14,display:"flex",alignItems:"center",gap:8,fontWeight:600}}><IconWind/> Preview</div><canvas ref={miniCanvasRef} width={500} height={225} style={{width:"100%",height:200,borderRadius:6,background:"var(--bg-canvas)"}}/><div style={{marginTop:8,fontSize:9,color:running?"var(--accent-green)":"var(--accent-red)"}}>{running?"● Running":"○ Paused"}</div></div></div>
  </div>);}

function AboutView(){const{isDark}=useTheme();return(<div style={{maxWidth:700,display:"flex",flexDirection:"column",gap:20}}>
  <div><div style={{fontFamily:"'Outfit',sans-serif",fontSize:32,fontWeight:900,background:isDark?"linear-gradient(90deg,#40e8ff,#a080ff)":"linear-gradient(90deg,#0a7ea4,#7050cc)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",letterSpacing:2,marginBottom:8}}>AEROLAB</div><div style={{fontSize:11,color:"var(--text-muted)",letterSpacing:3,marginBottom:6}}>LATTICE BOLTZMANN CFD WIND TUNNEL</div><div style={{fontSize:10,color:"var(--text-dim)",letterSpacing:1.5}}>A project by <a href="https://f1stories.gr" target="_blank" rel="noopener noreferrer" style={{color:"var(--accent-cyan)",textDecoration:"none",fontWeight:600,borderBottom:"1px solid var(--accent-cyan-border)"}}>f1stories.gr</a></div></div>
  <div style={{background:"var(--bg-panel)",border:"1px solid var(--border-primary)",borderRadius:10,padding:16}}><div style={{fontSize:9,color:"var(--text-muted)",letterSpacing:3,textTransform:"uppercase",marginBottom:14,display:"flex",alignItems:"center",gap:8,fontWeight:600}}><IconLayers/> Overview</div><p style={{fontSize:12,lineHeight:1.9,color:"var(--text-secondary)",margin:0}}>AeroLab uses a Lattice Boltzmann D2Q9 solver — the same class of algorithm used in professional CFD. Unlike simplified schemes, LBM naturally captures vortex shedding, wake turbulence, and boundary layer separation. The {COLS}×{ROWS} grid ({(COLS*ROWS).toLocaleString()} cells) uses BGK collision, Zou-He inlet BCs, and bounce-back walls. Particles use RK2 midpoint integration with bilinear velocity interpolation. Built by f1stories.gr.</p></div>
  <div style={{background:"var(--bg-panel)",border:"1px solid var(--border-primary)",borderRadius:10,padding:16}}><div style={{fontSize:9,color:"var(--text-muted)",letterSpacing:3,textTransform:"uppercase",marginBottom:14,display:"flex",alignItems:"center",gap:8,fontWeight:600}}><IconGear/> Features</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginTop:8}}>{[{title:"LBM D2Q9 Solver",desc:"BGK collision, 72k cell grid, bounce-back solid walls"},{title:"4 Visualization Modes",desc:"Velocity, pressure, streamlines, vorticity (curl)"},{title:"RK2 Particle Tracer",desc:"Midpoint integration + bilinear interpolation for accurate pathlines"},{title:"Zou-He Boundaries",desc:"Proper inlet velocity BC, zero-gradient outlet"},{title:"Bilinear Heatmap",desc:"Per-pixel interpolation with Turbo & CoolWarm colormaps"},{title:"Live Telemetry",desc:"CL, CD, Re, regime, FPS, CSV export"}].map(({title,desc})=><div key={title} style={{padding:"14px 16px",borderRadius:8,background:isDark?"rgba(10,30,52,0.5)":"rgba(220,232,244,0.5)",border:"1px solid var(--border-primary)"}}><div style={{fontSize:11,color:"var(--accent-cyan)",fontWeight:600,marginBottom:6,letterSpacing:1}}>{title}</div><div style={{fontSize:10,color:"var(--text-muted)",lineHeight:1.7}}>{desc}</div></div>)}</div></div>
  <div style={{textAlign:"center",padding:"24px 0 8px",borderTop:"1px solid var(--border-primary)"}}><a href="https://f1stories.gr" target="_blank" rel="noopener noreferrer" style={{fontFamily:"'Outfit',sans-serif",fontSize:14,fontWeight:700,color:"var(--accent-cyan)",textDecoration:"none",letterSpacing:2}}>f1stories.gr</a><div style={{fontSize:9,color:"var(--text-faint)",marginTop:6,letterSpacing:1.5}}>AERODYNAMICS • MOTORSPORT • ENGINEERING</div></div>
</div>);}
